version: "3.8"

services:
  database:
    image: postgres:14.6-alpine
    container_name: db_app
    env_file:
     - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    container_name: redis_app
    hostname: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["sh", "/fastapi_app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis

volumes:
  postgres_data: