"""Test migration

Revision ID: d11ea899588f
Revises: 07360bd27636
Create Date: 2024-07-08 21:35:53.266925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11ea899588f'
down_revision: Union[str, None] = '07360bd27636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=False))
    op.drop_constraint('users_firstname_key', 'users', type_='unique')
    op.drop_constraint('users_lastname_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_lastname_key', 'users', ['lastname'])
    op.create_unique_constraint('users_firstname_key', 'users', ['firstname'])
    op.drop_column('users', 'phone')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
